---
- name: Deny root login
  become: yes
  become_method: sudo
  become_user: root
  lineinfile: >-
    dest='/etc/ssh/sshd_config'
    line='PermitRootLogin no'
    regexp='^PermitRootLogin without-password'
    backrefs=yes
    state=present

