---
- name: Add docker apt key
  become: yes
  become_method: sudo
  become_user: root
  apt_key: >-
    keyserver='hkp://p80.pool.sks-keyservers.net:80'
    id='58118E89F3A912897C070ADBF76221572C52609D'
    state=present

- name: Set packages
  become: yes
  become_method: sudo
  become_user: root
  apt_repository: >-
    repo='{{ item }} https://apt.dockerproject.org/repo ubuntu-trusty main'
    state=present
  with_items:
    - "deb"
