---
- name: Add nginx apt key
  become: yes
  become_method: sudo
  become_user: root
  apt_key: url='http://nginx.org/keys/nginx_signing.key' state=present

- name: Set packages
  become: yes
  become_method: sudo
  become_user: root
  apt_repository: >-
    repo='{{ item }} http://nginx.org/packages/ubuntu/ trusty nginx'
    state=present
  with_items:
    - "deb"
    - "deb-src"

- name: Install nginx
  become: yes
  become_method: sudo
  become_user: root
  apt: >-
    name=nginx
    state=latest
    update_cache=yes
    cache_valid_time=3600
  notify: Restart nginx

- name: Set proxy host
  become: yes
  become_method: sudo
  become_user: root
  lineinfile: >-
    dest='/etc/nginx/conf.d/default.conf'
    line='    proxy_set_header {{ item.key }} {{ item.value }};'
    insertbefore='^}'
  with_items:
    - key: "Host"
      value: "$host"
    - key: "X-Forwarded-For"
      value: "$proxy_add_x_forwarded_for"
    - key: "X-Forwarded-Host"
      value: "$host"
    - key: "X-Forwarded-Server"
      value: "$host"
    - key: "X-Real-IP"
      value: "$remote_addr"
  notify: Restart nginx

- name: Replace charset
  become: yes
  become_method: sudo
  become_user: root
  lineinfile: >-
    dest='/etc/nginx/conf.d/default.conf'
    regexp='    charset koi8-r;'
    line='    charset utf-8;'
    state=present
    backrefs=yes
  notify: Restart nginx

- name: Unset log
  become: yes
  become_method: sudo
  become_user: root
  lineinfile: >-
    dest='/etc/nginx/conf.d/default.conf'
    regexp='    access_log  /var/log/nginx/log/host.access.log  main;'
    line='    #access_log  /var/log/nginx/log/host.access.log  main;'
    state=present
    backrefs=yes
  notify: Restart nginx
